app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('redfort/',redfort,name='redfort'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
    path('charminar/',charminar,name='charminar'),
    path('tajmahal/',tajmahal,name='tajmahal'),
]

project14/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def redfort(request):
    return render(request,'red fort.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def tajmahal(request):
    return render(request,'taj mahal.html')
def charminar(request):
    return render(request,'charminar.html')

templates/charminar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>this page belogs to app2</h1>
    <center><h1>ABOUT CHARMINAR</h1></center>
    <center><img src="https://th.bing.com/th/id/OIP.R9ohYI7KfGZE0v3TQ3VPSwHaIc?w=167&h=189&c=7&r=0&o=5&dpr=1.3&pid=1.7" alt=""></center>
    <p>Charminar is one of the oldest monuments in India, and it is situated in Hyderabad, Telangana. Charminar was built in 1591 and is a symbol of Hyderabad. This monument is the official emblem of Telangana. Charminar is derived from Urdu, meaning ‘Four Pillars.’ BYJU’S essay on Charminar helps us learn about the monument.
 Charminar was constructed by the fifth emperor of the Qutb Shahi dynasty, Muhammad Quli Qutb Shah. He built this monument after shifting the capital to Hyderabad from Golconda. The Archeological Survey of India (ASI) is a department that preserves the ancient monuments in the country. Charminar has a mosque that represents the Indo-Islamic style of architecture. In addition, festivals like Ramadan or Ramzan are celebrated here, and people around the world visit this place all over the year. Let us learn some exciting facts about Charminar by reading an essay on Charminar in English.
    </p>
    <center>
    <a href="{% url 'app1:redfort' %}">RED FORT</a>
    <a href="{% url 'app2:tajmahal' %}">TAJ MAHAL</a>
    </center>
</body>
</html>

templates/red fort.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>this page belogs to app1</h1>
    <center><h1 style="color: darkred;">RED-FORT</h1></center>
    <center><img src="https://th.bing.com/th?id=OIP.L8O0VdF301araAAEroMrywHaFj&w=288&h=216&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2" alt=""></center>
    <p>This monument embraces the utmost significance in Modern Indian History. It is made of Red Sandstone alone. Sited in central Delhi it was placed where the Mughal emperors lived for many periods. Red Fort was a magnificent castle coated with precious jewels but the Britishers looted these precious jewels during their empowerment over India.
Since Delhi was the capital of India until the British men shifted it, Red Fort was the control place for the whole nation. Built on the banks of Yamuna River, the walls of this magnificence fort have been built from 30 meters high Sandstone. It is supposed that Red Fort was made after 9 years of hard work of numerous masons for day and night during all seasons.
    </p>
    <center>
        <a href="{% url 'app2:tajmahal' %}">TAJ MAHAL</a>
        <a href="{% url 'app2:charminar' %}">CHARMINAR</a>
    </center>
    

</body>
</html>

templates/taj mahal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>this page belogs to app2</h1>
    <center><h1>ABOUT TAJ MAHAL</h1></center>
    <center><img src="https://th.bing.com/th?id=OIP.8K5n5BCqaT4RhvQjWwPedQHaFo&w=286&h=218&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2" alt=""></center>
    <p>
       <h1>A Symbol of Love</h1>
        The Taj Mahal was listed as a UNESCO World Heritage site in 1983 and is regarded as one of the most exquisite structural compositions in the entire world. After Mumtaz Mahal passed away, Shah Jahan erected the Taj Mahal in her honour and as a memorial. According to legend, Shah Jahan gave his wife the Taj Mahal as a gift. It is regarded as a representation of love and the tie between a husband and wife. It's interesting to note that the Taj Mahal is thought to represent Mumtaz's various emotions because it appears pinkish in the morning, milky white in the evening, and golden when the moon is out. 
        When Shah Jahan's wife was alive, he made her four vows. These commitments include constructing the Taj, getting remarried, going to the grave on each anniversary of his passing, and being kind to his kids. After two years, he decided to erect a memorial in her honour. Therefore, he decided to create a unique monument that had never been built before. With the help of 20,000 workers, he made the Taj Mahal—turning his vision into reality. The Taj Mahal's construction took 22 years to complete. Additionally, it was said that Shah Jahan had all 20,000 labourers' hands amputated to prevent them from ever again constructing monuments of this nature.
    </p>
    <center>
    <a href="{% url 'app1:redfort' %}">RED FORT</a>
    <a href="{% url 'app2:charminar' %}">CHARMINAR</a>
    </center>
</body>
</html>